[package]
name = "raylib_sandbox"
version = "0.0.1"
authors = "Civitasv"
description = "Raylib Sandbox"
license = "MIT"
default-run = "sandbox"

[profile]
vcpkg = false
c_compiler = "clang"
cxx_compiler = "clang++"
generator = "Ninja"
linker = "lld"
debugger = "lldb" # "lldb", "gdb", "code"
build-type = "Debug" # "Debug", "Release", "RelWithDebInfo", "MinSizeRel".
build-directory = "out/debug"
compile_commands = true
